version: '3.8'

x-dev:
    &proxy_conf
    http_proxy: "${http_proxy}"
    https_proxy: "${https_proxy}"
services:
    python_scripts_service:
        container_name: ${APP_NAME}
        image: python:3
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        #     args: *proxy_conf
        # image: ${APP_NAME}_img
        working_dir: /app
        environment:
            http_proxy: "${http_proxy}"
            https_proxy: "${https_proxy}"
        volumes:
        - '.:/app'
        restart: always
        command: tail -f /dev/null
